### ISSUE TITLE
Delete tag is not affect on value

### ISSUE THREAD

**Issue by timphamcmc** [fee-pg/antd-tag-input#111]
Re-proceduce the bug:

- Input 123 1234 123
- Then it will display Tag 123 already exist!
- Delete 123 at the top
- Then try to re-input 123 at the last
-  It display Tag 123 already exist! again

![image](https://user-images.githubusercontent.com/108319981/229971750-3b557ccf-aca6-4a31-8be1-02740fe341eb.png)

**Comment by fee-pg** [comment]
Thank you for your feedback. It has been fixed. Please upgrade to the new version to see the changes.
